config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :setup do
    resource :config, only: [:show]
  end

  get 'auth/new',     as: :login
  get 'auth/remove',  as: :logout
  get 'auth/callback'

  resources :internal_transfers, only: [:new, :create, :show], path_names: { new: '' }
  resources :transactions, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_complete_setup

  include Authentication

  private

  def require_complete_setup
    redirect_to setup_config_path if EnvConfig.incomplete?
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def new
    redirect_to fidor_api.authorize_start(
      redirect_uri: Rails.application.config.x.fidor_api.callback_url
    )
  end

  def callback
    session[:fidor_api_token] = fidor_api.authorize_complete(
      redirect_uri: Rails.application.config.x.fidor_api.callback_url,
      code:         params[:code]
    ).to_h

    redirect_to root_path
  end

  def remove
    session.delete(:fidor_api_token)
    redirect_to root_path
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper_method :logged_in?
    helper_method :current_account
    helper_method :current_customer
    helper_method :current_user
  end

  def self.included(base)
    base.rescue_from Faraday::ClientError do |e|
      raise e if e.response[:status] != 401
      redirect_to logout_path
    end
  end

  private

  def require_valid_session
    unless logged_in?
      session[:forward] = request.original_url
      redirect_to login_path
    end
  end

  def logged_in?
    session[:fidor_api_token].present?
  end

  def current_account
    @current_account ||= fidor_api.accounts.first
  end

  def current_customer
    @current_customer ||= fidor_api.customers.first
  end

  def current_user
    @current_user ||= fidor_api.user
  end

  private

  def fidor_api
    client = FidorApi::Client.new do |config|
      config.environment   = Rails.application.config.x.fidor_api.environment
      config.client_id     = Rails.application.config.x.fidor_api.client_id
      config.client_secret = Rails.application.config.x.fidor_api.client_secret
      config.logger        = TaggedLogger.new("FidorApi", Rails.logger)
    end

    client.token = FidorApi::Token.new(session[:fidor_api_token]) if logged_in?
    client
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/internal_transfers_controller.rb
class InternalTransfersController < ApplicationController
  before_action :require_valid_session

  def new
    @transfer = fidor_api.new_internal_transfer
  end

  def create
    if (@transfer = fidor_api.create_internal_transfer(transfer_params)) && @transfer.persisted?
      redirect_to internal_transfer_path(@transfer.id), flash: { success: "Transfer has been successfully created" }
    else
      render :new
    end
  end

  def show
    @transfer = fidor_api.internal_transfer(params[:id])
  end

  private

  def transfer_params
    params.require(:transfer_internal).permit(:receiver, :amount, :subject).tap do |params|
      params[:amount]       = params[:amount].present? ? BigDecimal.new(params[:amount]) : nil
      params[:account_id]   = current_account.id
      params[:external_uid] = SecureRandom.hex(8)
    end
  end
end

app/controllers/setup/base_controller.rb
class Setup::BaseController < ApplicationController
  skip_before_action :require_complete_setup

  before_action :require_incomplete_setup

  layout "setup"

  def index
  end

  private

  def require_incomplete_setup
    redirect_to root_path if Rails.env.production? && !EnvConfig.incomplete?
  end

end

app/controllers/setup/configs_controller.rb
class Setup::ConfigsController < Setup::BaseController
  def show
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :require_valid_session

  def index
    @transactions = fidor_api.transactions(pagination)
  end

  def show
    @transaction = fidor_api.transaction params[:id]
  end

  private

  def pagination
    {
      page:     params[:page] || 1,
      per_page: 10
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_currency(amount)
    number_to_currency amount, unit: "&euro;".html_safe, format: "%n %u"
  end
end

app/helpers/controllers_helper.rb
module ControllersHelper
  def namespace?(*controller)
    controller.include?(params[:controller].split('/').first)
  end

  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end

  def is_active?(link_path, return_class = "active")
    current_page?(link_path) ? return_class : nil
  end
end

app/helpers/error_messages_helper.rb
# encoding: utf-8
# Nifty Generators - https://github.com/ryanb/nifty-generators
#
# copy from Nifty Generators,
# markup optimized for bootstrap
#
# Usage:
#    <%= f.error_messages %>
#    <%= error_messages_for(@object) %>
#
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t("errors.template.header", count: objects[0].errors.size, model: objects[0].class.model_name.human)
    options[:message] ||= I18n.t("errors.template.body")
    messages = objects.compact.flat_map { |o| o.errors.full_messages }
    unless messages.empty?
      content_tag(:div, class: "alert alert-danger alert-dismissible alert-form ") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:a, "&times;".html_safe, href: "#", class: "close", 'data-dismiss': "alert") +
        content_tag(:h4, options[:header_message], class: "h5 mt-1") +
        content_tag(:p, options[:message], class: "mb-0") +
        content_tag(:ul, list_items.join.html_safe, class: "mb-0")
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/views/application/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, body| %>
    <%= content_tag :div, class: "alert alert-#{type} alert-dismissible alert-flash" do %>
      <span class="close" data-dismiss="alert">&times;</span>
      <% if body.kind_of?(Array) %>
        <ul class="mb-0">
          <% body.each do |message| %>
            <%= content_tag(:li, message) %>
          <% end %>
        </ul>
      <% else %>
        <%= content_tag(:p, body, class: "mb-0") %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/application/_footer.html.erb
<div class="my-5">
  <p class="text-center text-muted small">🍺 Handcrafted in Bavaria. 🥨</p>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container">

    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa fa-anchor fa-2x text-success align-middle"></i> Fidor API
      <small class="text-muted">Demo</small>
    <% end %>


    <% if logged_in? %>
      <span class="navbar-text ml-auto">
        <strong><%= current_customer.first_name %> <%= current_customer.last_name %></strong>
      </span>
      <form class="form-inline">
        <%= link_to logout_path, class: "btn btn-outline-danger btn-sm ml-4" do %>
          <i class="fa fa-sign-out"></i> Logout
        <% end %>
      </form>

    <% else %>
      <span class="navbar-text ml-auto">
        Hey Guest
      </span>
      <form class="form-inline">
        <%= link_to login_path, class: "btn btn-outline-success btn-sm ml-4" do %>
          <i class="fa fa-sign-in"></i> Login
        <% end %>
      </form>
    <% end %>

  </div>
</nav>

app/views/application/_navigation.html.erb
<ul class="nav nav-pills justify-content-center my-4">
  <%= content_tag :li, class: "nav-item" do %>
    <%= link_to "Details", root_path, class: "nav-link #{is_active?(root_path)}" %></li>
  <% end %>

  <%= content_tag :li, class: "nav-item" do %>
    <%= link_to "Transactions", transactions_path, class: "nav-link #{controller?('transactions') ? "active" : nil}" %></li>
  <% end %>

  <%= content_tag :li, class: "nav-item" do %>
    <%= link_to "Internal Transfer", new_internal_transfer_path, class: "nav-link #{controller?('internal_transfers') ? 'active' : nil}" %></li>
  <% end %>
</ul>

app/views/home/_account.html.erb
<div class="card">
  <div class="card-body">
    <i class="fa fa-bank fa-3x float-right"></i>
    <h4 class="card-title">Account</h4>
    <h6 class="card-subtitle mb-2 text-muted">Details</h6>
    <hr />
    <dl class="row mb-0">
      <dt class="col-sm-5">IBAN</dt>
      <dd class="col-sm-7"><%= current_account.iban %></dd>

      <dt class="col-sm-5">Account number</dt>
      <dd class="col-sm-7"><%= current_account.account_number %></dd>

      <dt class="col-sm-5">Balance</dt>
      <dd class="col-sm-7"><%= format_currency current_account.balance %></dd>

      <dt class="col-sm-5">Overdraft</dt>
      <dd class="col-sm-7"><%= format_currency current_account.overdraft %></dd>

      <dt class="col-sm-5">Preauth amount</dt>
      <dd class="col-sm-7"><%= format_currency current_account.preauth_amount %></dd>

      <dt class="col-sm-5">Balance available</dt>
      <dd class="col-sm-7"><%= format_currency current_account.balance_available %></dd>
    </dl>
  </div>
</div>

app/views/home/_customer.html.erb
<div class="card mb-4">
  <div class="card-body">
    <i class="fa fa-user fa-3x float-right"></i>
    <h4 class="card-title">Customer</h4>
    <h6 class="card-subtitle mb-2 text-muted">Details</h6>
    <hr />
    <dl class="row mb-0">
      <dt class="col-sm-5">Fidor ID</dt>
      <dd class="col-sm-7"><%= current_customer.id %></dd>

      <dt class="col-sm-5">Firstname</dt>
      <dd class="col-sm-7"><%= current_customer.first_name %></dd>

      <dt class="col-sm-5">Lastname</dt>
      <dd class="col-sm-7"><%= current_customer.last_name %></dd>

      <dt class="col-sm-5">Street / Street-No.</dt>
      <dd class="col-sm-7"><%= current_customer.adr_street %> <%= current_customer.adr_street_number %></dd>

      <dt class="col-sm-5">ZIP-Code / City</dt>
      <dd class="col-sm-7"><%= current_customer.adr_post_code %> <%= current_customer.adr_city %></dd>

      <dt class="col-sm-5">Country</dt>
      <dd class="col-sm-7"><%= current_customer.adr_country %></dd>
    </dl>
  </div>
</div>

app/views/home/index.html.erb
<% if logged_in? %>
  <div class="row justify-content-center">
    <div class="col-11 col-md-8 col-lg-6 col-xl-5">
      <%= render "customer" %>
    </div>
    <div class="col-11 col-md-8 col-lg-6 col-xl-5">
      <%= render "account" %>
    </div>
  </div>

<% else %>
  <div class="p-5 text-center text-muted">
    <i class="fa fa-minus-circle fa-4x mb-3"></i>
    <p class="lead mb-1">You are not logged in</p>
    <p>Use the button to start an authentication</p>
    <%= link_to login_path, class: "btn btn-outline-secondary px-4" do %>
      <i class="fa fa-sign-in"></i> Login
    <% end %>
  </div>
<% end %>

app/views/internal_transfers/_form.html.erb
<%= simple_form_for @transfer, url: internal_transfers_path do |f| %>

  <%= f.error_messages %>

  <%= f.input :receiver, input_html: { autofocus: true } %>
  <%= f.input :amount, placeholder: "0.00", input_html: { data: { vm_mask_money: true } } %>
  <%= f.input :subject %>

  <%= f.button :submit, "Send Money Now", class: "btn btn-primary px-4" %>

<% end %>

app/views/internal_transfers/new.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-9 col-lg-7 col-xl-6">
    <h4>New Internal Transfer</h4>
    <p class="text-muted">Send Money to other Fidor Account by Nickname, E-Mail or Fidor ID.</p>

    <%= render "form" %>
  </div>
</div>

app/views/internal_transfers/show.html.erb
<div class="row justify-content-center">
  <div class="col-10 col-md-8 col-lg-6">
    <table class="table">
      <tr>
        <th>Receiver</th>
        <td><%= @transfer.receiver %></td>
      </tr>
      <tr>
        <th>Subject</th>
        <td><%= @transfer.subject %></td>
      </tr>
      <tr>
        <th>Amount</th>
        <td><%= format_currency @transfer.amount %></td>
      </tr>
      <tr>
        <th>Created at</th>
        <td><%= l @transfer.created_at %></td>
      </tr>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<% content_for :body do %>
  <%= render "navbar" %>

  <div class="container">
    <%= render "navigation" if logged_in? %>

    <%= render "flash" %>

    <%= yield %>

    <%= render "footer" %>
  </div>
<% end %>

<%= render template: "layouts/application_base" %>

app/views/layouts/application_base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fidor API Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag    "//maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome-font-awesome.min.css" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= content_for?(:body) ? yield(:body) : yield %>
  </body>
</html>

app/views/layouts/setup.html.erb
<% content_for :body do %>
  <div class="container py-5">
    <%= yield %>
  </div>
<% end %>

<%= render template: "layouts/application_base" %>

app/views/setup/configs/show.html.erb
<% if EnvConfig.incomplete? %>
  <h2>Incomplete Configuration detected</h2>

  <p class="lead">
    Please make sure all options are flagged as status "OK" (<i class="fa fa-check text-success"></i>).
  </p>
  <p>
    <i class="fa fa-exclamation-circle text-warning fa-2x align-middle"></i>
    <small><strong>Note:</strong> It might be required to restart the application in order to have your changes taking effect.</small>
  </p>
<% else %>
  <h2>
    <i class="fa fa-check text-success"></i>
    Complete Configuration detected
  </h2>

  <p class="lead">
    Your configuration looks complete.
    Try to access the application at the <%= link_to "root path", root_path %>
  </p>
<% end %>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th>Status</th>
      <th>Option</th>
      <th>Current value</th>
    </tr>
  </thead>
  <tbody>
    <% EnvConfig::REQUIRED_KEYS.each do |key| %>
      <tr>
        <td class="text-center">
          <% if EnvConfig.present?(key) %>
            <i class="fa fa-check text-success"></i>
          <% else %>
            <i class="fa fa-times text-danger"></i>
          <% end %>
        </td>
        <td>
          <code><%= key %></code>
        </td%>
        <td>
          <code><%= EnvConfig.get(key) %></code>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, body| %>
    <%= content_tag :div, class: "alert alert-#{type} alert-flash" do %>
      <span class="delete"><!--//--></span>
      <% if body.kind_of?(Array) %>
        <ul>
          <% body.each do |message| %>
            <%= content_tag(:li, message) %>
          <% end %>
        </ul>
      <% else %>
        <%= content_tag(:p, body) %>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <br />
<% end %>

app/views/transactions/index.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-9 col-lg-7 col-xl-6">
    <table class="table table-striped">
      <colgroup>
        <col width="25%">
        <col width="45%">
        <col width="30%">
      </colgroup>
      <tr>
        <th>
          Booking Date<br />
          <small>Value Date</small>
        </th>
        <th>
          Subject<br />
          <small>Type</small>
        </th>
        <th class="text-right">Amount</th>
      </tr>
      <% @transactions.each do |t| %>
        <tr>
          <td>
            <%= l t.booking_date.to_date rescue "-" %><br />
            <small class="text-muted"><%= l t.value_date.to_date rescue "-" %></small>
          </td>
          <td>
            <%= link_to t.subject, t %><br />
            <small class="text-muted"><%= t.transaction_type %></small>
          </td>
          <td class="align-middle text-right"><%= format_currency t.amount %></td>
        </tr>
      <% end %>
    </table>

    <div class="my-5">
      <%= paginate @transactions %>
    </div>

  </div>
</div>

app/views/transactions/show.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-9 col-lg-7 col-xl-6">
    <table class="table table-striped">
      <colgroup>
        <col width="25%">
        <col width="45%">
      </colgroup>
      <% @transaction.attributes.each do |key, value| %>
        <tr>
          <th><%= key.to_s.humanize %></th>
          <td>
            <%=
              case value
              when Hash
                "<pre>#{value.to_yaml}</pre>".html_safe
              else
                value.presence || '-'
              end
            %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>